version: '3.9'

services:
  db:
    container_name: '${DB_NAME}'
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    ports:
      - '${DB_PORT}:5432'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD}'
    ports:
      - '${PGADMIN_PORT}:80'
